### PR TITLE
Update dependencies, Gradle, JDK

### PR DESCRIPTION
**Pull request by cyb3rko**
Moin!

First of all thank you for this library.  
With this PR a few updates take place:

- Update Gradle 7.4.2 -> 8.1.1
- Update Android Gradle Plugin 7.2.0 -> 8.1.0
- Update JDK 1.8 -> 17
- Improve Gradle properties
- Include 'release' publishing variant (reference: https://stackoverflow.com/questions/71365373/software-components-will-not-be-created-automatically-for-maven-publishing-from)

⚠️ I can not guarantee that the maven publish library works as expected, but at least the build error is resolved.

### CODE REVIEW

**Comment by lambdapioneer** [comment]
Hi! Thanks for the taking the time and submitting the PR!

Just wanted to say that it might take a while until I get the chance to test this locally and then review the changes. However, this does not seem time critical and actually might be best to test when doing the next release anyway.

**Comment by cyb3rko** [comment]
Yep, no problem. Maybe until then I can find some time to work on the tests and fix them.

**Comment by cyb3rko** [comment]
Just opened the project again and all tests seem to work, I don't know what I've done wrong last time.  
But now I have some more updates to commit again.

**Comment by lambdapioneer** [comment]
Thanks for this! Tested and all seems to work.

**Pull request merged**
